name: glencee
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  dio: ^3.0.8
  shared_preferences: ^0.5.6+1
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+11



dev_dependencies:
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_min.png"


flutter:


  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: Bahij
      fonts:
        - asset: assets/fonts/Bahij_TheSansArabic-ExtraLight.ttf
